Added git checkout -b description
bikol/ZINO2021 pull request #6
Opened 2020-12-23 15:58 UTC by s329416

2020-12-28 13:15 UTC, bikol requested changes
proszę zrobić merge z obecnym stanem repozytorium

2020-12-30 19:56 UTC, s329416 commented
Gotowe.
Sprawdziłem zmiany i widzę, że mój edytor sformatował plik i usunął dwa białe znaki. Nie cofałem już tych zmian.

2021-01-03 12:45 UTC, bikol requested changes
Dalej jest konflikt, proszę zrobic merge z obecnym stanem repozytorium

2021-01-03 16:02 UTC, s329416 commented
Rozwiązałem konflikt. Tym razem wziąłem wszystko z głównego brancha poza moim opisem.

2021-01-03 16:04 UTC, merged